language: python
group: travis_latest

addons:
  apt:
    packages: gfortran

before_install:
- pip install -e .[tests,lint]
- pip install cmake

install:
- cmake -B build
- cmake --build build

script:
- flake8
- mypy .
- pytest
