language: python
group: travis_latest

addons:
  apt:
    packages:
      - gfortran

before_install:
- pip install cmake
- pip install -e .

install:
- cmake -B dir.source -S dir.source/dir.obj
- cmake --build dir.source/dir.obj
