language: python
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.6

os:
- linux

addons:
  apt:
    packages:
    - gfortran

install: pip install -e .[tests]

script: 
- pytest -xrsv
- flake8
- mypy . --ignore-missing-imports


after_success: 
- pytest --cov --cov-config=setup.cfg 
- coveralls
