language: c

os:
  - linux
  
dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran


script: 
    - cd transcar/dir.source/dir.obj
    - cmake ..
    - make 
    - cd ../..

