language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

dist: trusty
group: edge
  
env: FC=gfortran

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

install: python -m pip install -e .[tests]

script: coverage run tests/test.py -v

after_success: coveralls
