language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.6

os:
- linux

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: gfortran-6

install:
- pip install -e .[tests]
- cd $TRAVIS_BUILD_DIR/dir.source/dir.obj
- cmake ..
- cmake --build . -j

script:
- cd $TRAVIS_BUILD_DIR
- pytest -xrsv
- flake8
- mypy .


after_success:
- pytest --cov
- coveralls
