name: ci_unix

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - "**.py"
      - ".github/workflows/ci_unix.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install prereqs
      run: pip install -e .[tests,lint]

    - run: flake8
    - run: mypy

    - run: cmake -B build
    - run: cmake --build build --parallel

    - run: pytest
